#!/usr/bin/env bun

/**
 * Encrypt a JS bundle file with AES-256-GCM using the key generated by
 * `scripts/generate-key.ts`.
 *
 * Usage: encrypt-bundle.ts <input-path> <output-path>
 *
 * Format: [nonce: 12 bytes][ciphertext + GCM tag: N + 16 bytes]
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as crypto from "node:crypto";

const REPO_ROOT = path.join(import.meta.dir, "..");
const KEY_TMP = path.join(REPO_ROOT, "crates", "pi-natives", "key.tmp");

function main(): void {
	if (!fs.existsSync(KEY_TMP)) {
		throw new Error(
			`${KEY_TMP} not found. Run 'bun run generate-key' first.`,
		);
	}

	const keyHex = fs.readFileSync(KEY_TMP, "utf-8").trim();
	const key = Buffer.from(keyHex, "hex");

	if (key.length !== 32) {
		throw new Error(`Key must be 32 bytes, got ${key.length}`);
	}

	const inputPath = process.argv[2];
	const outputPath = process.argv[3];
	if (!inputPath || !outputPath) {
		throw new Error("Usage: encrypt-bundle.ts <input-path> <output-path>");
	}

	const plaintext = fs.readFileSync(inputPath);

	if (plaintext.length === 0) {
		throw new Error(`Input file is empty: ${inputPath}`);
	}

	// Generate a fresh random nonce for each encryption (GCM requirement)
	const nonce = crypto.getRandomValues(new Uint8Array(12));

	console.log(`Encrypting ${plaintext.length} bytes from ${inputPath}...`);

	// AES-256-GCM encrypt
	const cipher = crypto.createCipheriv("aes-256-gcm", key, nonce);
	const encrypted = Buffer.concat([cipher.update(plaintext), cipher.final()]);
	const tag = cipher.getAuthTag();

	// Output: nonce (12) + ciphertext (N) + tag (16)
	fs.mkdirSync(path.dirname(outputPath), { recursive: true });
	const outFile = fs.openSync(outputPath, "w");
	fs.writeSync(outFile, nonce);
	fs.writeSync(outFile, encrypted);
	fs.writeSync(outFile, tag);
	fs.closeSync(outFile);

	const totalSize = nonce.length + encrypted.length + tag.length;
	console.log(`Wrote ${totalSize} bytes to ${outputPath}`);
}

main();
