#!/usr/bin/env bun

/**
 * Encrypt a JS bundle file with a bundle-specific AES-256-GCM key derived from
 * the master key generated by `scripts/generate-key.ts`.
 *
 * Usage: encrypt-bundle.ts <input-path> <output-path> <bundle-id>
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { createEncryptedBundlePayload } from "./bundle-crypto";

const REPO_ROOT = path.join(import.meta.dir, "..");
const KEY_TMP = path.join(REPO_ROOT, "crates", "pi-natives", "key.tmp");

function main(): void {
	if (!fs.existsSync(KEY_TMP)) {
		throw new Error(
			`${KEY_TMP} not found. Run 'bun run generate-key' first.`,
		);
	}

	const keyHex = fs.readFileSync(KEY_TMP, "utf-8").trim();
	const key = Buffer.from(keyHex, "hex");

	if (key.length !== 32) {
		throw new Error(`Key must be 32 bytes, got ${key.length}`);
	}

	const inputPath = process.argv[2];
	const outputPath = process.argv[3];
	const bundleId = process.argv[4];
	if (!inputPath || !outputPath || !bundleId) {
		throw new Error("Usage: encrypt-bundle.ts <input-path> <output-path> <bundle-id>");
	}

	const plaintext = fs.readFileSync(inputPath);

	if (plaintext.length === 0) {
		throw new Error(`Input file is empty: ${inputPath}`);
	}

	console.log(`Encrypting ${plaintext.length} bytes from ${inputPath} as ${bundleId}...`);
	const payload = createEncryptedBundlePayload(key, bundleId, plaintext);
	key.fill(0);
	fs.mkdirSync(path.dirname(outputPath), { recursive: true });
	fs.writeFileSync(outputPath, payload);
	console.log(`Wrote ${payload.length} bytes to ${outputPath}`);
}

main();
